/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.text.Position;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Comp
 */
public class JavaApplication7 extends javax.swing.JFrame {

    static int lengthPath = 0;
    HashMap<String, MutableTreeNode> pathsNods = new HashMap<>();
    String oldPath = "";
    /**
     * Creates new form JavaApplication7
     */
    public JavaApplication7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Файлы");
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree2);

        jButton1.setText("Нарисовать дерево");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jButton1)))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTree2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //demonstrationFunction();
        //allFilesInConsole("C://Users//Comp//Desktop//app");
        
        initializeTree("C:\\Users\\Comp\\Desktop\\app");
        allFilesInTree("C:\\Users\\Comp\\Desktop\\app","java","a");
        //allFilesInTree("C:\\Users\\Comp\\Desktop\\app","*","a");
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaApplication7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaApplication7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaApplication7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaApplication7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaApplication7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables

    private void demonstrationFunction() {
        DefaultTreeModel model = (DefaultTreeModel)jTree2.getModel();
        
        //int startRow = 0;
        //String prefix = "J";
        //TreePath path = jTree1.getNextMatch(prefix, startRow, Position.Bias.Forward);
        
        //MutableTreeNode node = (MutableTreeNode)path.getLastPathComponent();
        // Или
        //MutableTreeNode node = (MutableTreeNode)path.getPath()[0];
        
        MutableTreeNode node = (MutableTreeNode)jTree2.getSelectionPath().getLastPathComponent();
        MutableTreeNode newNode = new DefaultMutableTreeNode("Green Elephant");
        model.insertNodeInto(newNode, node, node.getChildCount());
    }
    
    public void allFilesInConsole(String dirName){
	File dir = new File(dirName);
	if (!dir.isDirectory()) {
            return;
	}	
	
	File files[] = dir.listFiles();
	for (File file : files) {
            System.out.println(file.getAbsolutePath());
            allFilesInConsole(file.getAbsolutePath());
	}
    }
    
    public void initializeTree(String dirName) {
        TreePath path = jTree2.getNextMatch("Файлы", 0, Position.Bias.Forward);
        MutableTreeNode node = (MutableTreeNode)path.getLastPathComponent();
        pathsNods.put(dirName, node);
    }
    
    public void allFilesInTree(String dirName, String type, String find) {
	File dir = new File(dirName);
        if (!dir.isDirectory()) {
            return;
        }
        DefaultTreeModel model = (DefaultTreeModel)jTree2.getModel();

        MutableTreeNode newNode;
        MutableTreeNode parentNode;
        String strNode = "";
        String[] argsInDirName;
        
        File files[] = dir.listFiles();
	for (File file : files) {
            if(file.isFile()) {
                //String typeFile = "";
                // Что то не работает
                //typeFile = typeFile.substring(file.getName().indexOf('.'));
                
                if(file.getName().endsWith("." + type)) {
                    strNode = file.getName();
                }
                else if(type.equals("*")) {
                    strNode = file.getName();
                }
                else {
                    continue;
                }
                newNode = new DefaultMutableTreeNode(strNode);
                parentNode = pathsNods.get(dirName);
                
                // Что то фокус не удался - removeNodeFromParent не получился
                //MutableTreeNode threePointsNode = pathsNods.get(dirName+"\\...");
                //model.removeNodeFromParent(threePointsNode);
                
                if(pathsNods.containsKey(dirName+"\\...")) {
                    MutableTreeNode threePointsNode = pathsNods.get(dirName+"\\...");
                    threePointsNode.setUserObject(strNode);
                    pathsNods.remove(dirName+"\\...");
                    pathsNods.put(file.getAbsolutePath(),threePointsNode);
                }
                else {
                    model.insertNodeInto(newNode, parentNode, parentNode.getChildCount());
                    pathsNods.put(file.getAbsolutePath(), newNode);
                }
                
                // TODO: КакойТоТвойTextBox.setText(КакойТоТвойTextBox.getText() + findLineInFileByTxtSearch(file, find));
                // чтобы инфа о строчках где нашлось String find попала пользователю на экран
            }
            else {
                argsInDirName = file.getAbsolutePath().split("\\\\"); // типа в file
                // путь прописан через \\, а не через / или \ (видно на точке останова что через \\)
                // \\\\ - экранирование \\ в ""
                strNode = argsInDirName[argsInDirName.length - 1];
                
                newNode = new DefaultMutableTreeNode(strNode);
                parentNode = pathsNods.get(dirName);
                model.insertNodeInto(newNode, parentNode, parentNode.getChildCount());
                pathsNods.put(file.getAbsolutePath(), newNode);
                MutableTreeNode threePointsNode = new DefaultMutableTreeNode("...");
                model.insertNodeInto(threePointsNode, newNode, newNode.getChildCount());
                pathsNods.put(file.getAbsolutePath() + "\\...", threePointsNode);
            }
            
            // Вывод дерева в консоль
            //System.out.println(file.getAbsolutePath());
            
            allFilesInTree(file.getAbsolutePath(), type, find);
	}
    }

    private String findLineInFileByTxtSearch(File logFile, String find) {
        // Содержимое файла в String content
        String content = "";
        String response = "";
        boolean isFind = false;
        try {
            content = new String(Files.readAllBytes(Paths.get(logFile.getAbsolutePath())));
        } catch (IOException ex) {
            Logger.getLogger(JavaApplication7.class.getName()).log(Level.SEVERE, null, ex);
        }
        String[] contentLines = content.split("\r\n");
        for(int i = 0;i<contentLines.length;i++) {
            if(contentLines[i].contains(find)) {
                if(!isFind) {// Если ещё ничего не нашли
                    response += "In file " + logFile.getName() + " in path " + logFile.getAbsolutePath() +
                            " find in line " + (i+1) + ":\r\n";
                    isFind = true;
                }
                response = contentLines[i];
            }
        }
        if(isFind) {
            response += "/r/n"; // Отделим найденное от найденных в следующих файлах
                                // при повторном вызове findLineInFileByTxtSearch()
        }
        return response;
    }
}
